# -*- coding: utf-8 -*-
"""Untitled13 (1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VzMS_0llw_luxzVlaOau4YIPXYflAKp

#1. Install
"""

!pip install google-play-scraper
!pip install sastrawi

"""#2. Import Library"""

from google_play_scraper import app, reviews, Sort, reviews_all
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np
seed = 0
np.random.seed(seed)
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import re
import string
import urllib.request
import csv
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.util import ngrams
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from wordcloud import WordCloud
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, confusion_matrix,
                             accuracy_score, precision_score,
                             recall_score, f1_score)
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

print("✅ Semua library berhasil diimport!")

"""#3. Scraping Halodoc"""

import datetime
tanggal_scraping = datetime.datetime.now().strftime('%d %B %Y, %H:%M WIB')

result, _ = reviews(
    'com.linkdokter.halodoc.android',  # ID aplikasi Halodoc
    lang='id',         # ulasan bahasa Indonesia
    country='id',      # dari Play Store Indonesia
    sort=Sort.MOST_RELEVANT,
    count=1200         # ambil lebih dari 1000 biar aman
)
scrapreview = result

print(f"✅ Total ulasan berhasil di-scrape: {len(scrapreview)}")
print(f"📅 Tanggal scraping  : {tanggal_scraping}")
print(f"📱 Sumber            : Google Play Store (ID)")
print(f"🔗 App ID            : com.linkdokter.halodoc.android")
print(f"🛠️  Tools             : google-play-scraper (Python)")
print(f"🌐 Bahasa ulasan     : Indonesia")

"""#4. Simpan ke CSV & Loading Dataset"""

# Simpan ke CSV (format sederhana dulu)
with open('ulasan_halodoc.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])
    for review in scrapreview:
        writer.writerow([review['content']])

print("File ulasan_halodoc.csv berhasil disimpan!")

# Load ke DataFrame lengkap
app_reviews_df = pd.DataFrame(scrapreview)
app_reviews_df.to_csv('ulasan_halodoc_full.csv', index=False)

jumlah_ulasan, jumlah_kolom = app_reviews_df.shape
print(f"Jumlah ulasan : {jumlah_ulasan}")
print(f"Jumlah kolom  : {jumlah_kolom}")
app_reviews_df.head()

"""#5. Eksplorasi & Bersihkan Data Awal"""

# Info dataset
app_reviews_df.info()

# Cek nilai kosong
print("\nNilai kosong per kolom:")
print(app_reviews_df.isnull().sum())

# Hapus kolom tidak dibutuhkan
cols_to_drop = [c for c in ['replyContent', 'repliedAt']
                if c in app_reviews_df.columns]
app_reviews_df = app_reviews_df.drop(columns=cols_to_drop)

clean_df = app_reviews_df.copy()
clean_df.info()

# Ambil 20 data pertama untuk uji coba
clean20_df = clean_df.head(20).copy()
clean20_df.info()

"""#6. Fungsi Preprocessing"""

# ── 1. Cleaning ──────────────────────────────────────────
def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text)    # hapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text)    # hapus hashtag
    text = re.sub(r'RT[\s]', '', text)            # hapus RT
    text = re.sub(r"http\S+", '', text)           # hapus URL
    text = re.sub(r'[0-9]+', '', text)            # hapus angka
    text = re.sub(r'[^\w\s]', '', text)           # hapus karakter aneh
    text = text.replace('\u00a0', ' ')
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.strip()
    return text

# ── 2. Case Folding ──────────────────────────────────────
def casefoldingText(text):
    return text.lower()

# ── 3. Slang Word Fix ────────────────────────────────────
def fix_slangwords(text):
    slangwords = {
        # Negasi
        "gk":"tidak","gak":"tidak","ga":"tidak","nggak":"tidak",
        "enggak":"tidak","tdk":"tidak","tak":"tidak","ngga":"tidak",
        "kagak":"tidak",
        # Kata ganti
        "gue":"aku","gua":"aku","gw":"aku",
        "lu":"kamu","loe":"kamu","elo":"kamu","lo":"kamu","kmu":"kamu",
        # Umum
        "udh":"sudah","sdh":"sudah","udah":"sudah",
        "mau":"ingin","mw":"ingin","pengen":"ingin",
        "bgt":"sangat","banget":"sangat",
        "aja":"saja","doang":"saja",
        "kalo":"kalau","kl":"kalau",
        "trs":"terus","jg":"juga","jga":"juga","jd":"jadi",
        "sm":"sama","dgn":"dengan","tp":"tapi","tpi":"tapi",
        "krn":"karena","karna":"karena","pdhl":"padahal",
        "skrg":"sekarang","skr":"sekarang","sgt":"sangat",
        "bener":"benar","beneran":"benar-benar",
        "gimana":"bagaimana","gmna":"bagaimana",
        "knapa":"kenapa","knp":"kenapa",
        "yg":"yang","ny":"nya","dr":"dari",
        "nih":"ini","tuh":"itu",
        "btw":"omong-omong","mending":"lebih baik",
        "gpp":"tidak apa-apa","gapapa":"tidak apa-apa",
        "kmrn":"kemarin",
        "apaan":"apa","apasih":"apa","bkn":"bukan",
        "ttp":"tetap","sblumnya":"sebelumnya",
        "iya":"ya",
        # Konteks kesehatan & aplikasi
        "dok":"dokter","konsul":"konsultasi",
        "chat":"pesan","resep":"resep",
        "lemot":"lambat","lag":"lambat","ngelag":"lambat",
        "loading":"memuat","error":"kesalahan","bug":"gangguan",
        "login":"masuk","logout":"keluar",
        "otp":"kode verifikasi","verif":"verifikasi",
        "topup":"isi saldo","bayar":"pembayaran",
        "keren":"bagus","mantap":"bagus","mantul":"bagus sekali",
        "parah":"buruk","jelek":"buruk",
        "mksh":"terima kasih","makasih":"terima kasih",
        "tq":"terima kasih","thx":"terima kasih",
        "min":"admin",
        "wkwk":"","hehe":"","haha":"","sih":"","cuy":"",
        "anjir":"astaga","anjay":"astaga",
    }
    words = text.split()
    fixed = [slangwords.get(w.lower(), w) for w in words]
    return ' '.join(fixed)

# ── 4. Tokenizing ────────────────────────────────────────
def tokenizingText(text):
    return word_tokenize(text)

# ── 5. Stopword Removal ──────────────────────────────────
def filteringText(text):
    list_sw = set(stopwords.words('indonesian'))
    list_sw.update(set(stopwords.words('english')))
    list_sw.update(['iya','yaa','gak','nya','na','sih','ku','di',
                    'ga','ya','gaa','loh','kah','halodoc','app',
                    'aplikasi','woi','woii','woy','min','dok',
                    'halo','lah','deh','nih','dong'])
    return [w for w in text if w not in list_sw]

# ── 6. Stemming ──────────────────────────────────────────
factory = StemmerFactory()
stemmer = factory.create_stemmer()

exception_dict = {
    'perasaan':'perasaan','pelayanan':'pelayanan',
    'permasalahan':'permasalahan','pembayaran':'pembayaran',
    'kesehatan':'kesehatan','kemudahan':'kemudahan',
    'keamanan':'keamanan','kepuasan':'kepuasan',
    'keluhan':'keluhan','pertanyaan':'pertanyaan',
    'konsultasi':'konsultasi','pelayanan':'pelayanan',
}

def stemmingText(word_list):
    result = []
    for w in word_list:
        if w in exception_dict:
            result.append(exception_dict[w])
        else:
            result.append(stemmer.stem(w))
    return result

# ── 7. Join ke kalimat ───────────────────────────────────
def toSentence(list_words):
    return ' '.join(list_words)

print("✅ Semua fungsi preprocessing siap!")

"""#7. Preprocessing 20 Data (Uji Coba)"""

clean20_df['text_clean']           = clean20_df['content'].apply(cleaningText)
clean20_df['text_casefoldingText'] = clean20_df['text_clean'].apply(casefoldingText)
clean20_df['text_slangwords']      = clean20_df['text_casefoldingText'].apply(fix_slangwords)
clean20_df['text_tokenizingText']  = clean20_df['text_slangwords'].apply(tokenizingText)
clean20_df['text_stopword']        = clean20_df['text_tokenizingText'].apply(filteringText)
clean20_df['text_stemming']        = clean20_df['text_stopword'].apply(stemmingText)

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 80)
pd.set_option('display.expand_frame_repr', False)

clean20_df[['content','text_clean','text_slangwords',
            'text_stopword','text_stemming']].head(5)

"""#8. Tabel Preprocessing Manual 1 Ulasan"""

sample_review = clean_df['content'].iloc[0]
print("Ulasan asli:")
print(sample_review)
print()

step1 = cleaningText(sample_review)
step2 = casefoldingText(step1)
step3 = fix_slangwords(step2)
step4 = tokenizingText(step3)
step5 = filteringText(step4)
step6 = stemmingText(step5)

tabel = pd.DataFrame({
    'Tahap': ['1. Original','2. Cleaning','3. Case Folding',
              '4. Slangword Fix','5. Tokenizing',
              '6. Stopword Removal','7. Stemming'],
    'Hasil': [sample_review, step1, step2, step3,
              str(step4), str(step5), str(step6)]
})

pd.set_option('display.max_colwidth', None)
print("\nTabel 1. Contoh Hasil Pre-processing Teks Ulasan Halodoc")
print("(Menampilkan 7 tahap preprocessing pada 1 sampel ulasan)")
tabel

"""#9. Bigram Manual 1 Ulasan"""

bigrams_stopword = list(ngrams(step5, 2))
bigrams_stemmed  = list(ngrams(step6, 2))

bigram_df = pd.DataFrame({
    'Bigram (Stop Word Removal)': [' '.join(b) for b in bigrams_stopword],
    'Bigram (Stemming)'         : [' '.join(b) for b in bigrams_stemmed]
})

pd.set_option('display.max_colwidth', None)
print("Tokenisasi 2-gram (Bigram) dari 1 Ulasan Sampel:")
bigram_df

"""#10. WordCloud 20 Data"""

# Word Cloud dari 20 data sample — gambaran awal sebelum preprocessing full
text_stemming_all = ' '.join(
    clean20_df['text_stemming'].apply(lambda x: ' '.join(x) if isinstance(x, list) else str(x))
)

wordcloud = WordCloud(
    width=1200, height=600,
    background_color='white',
    colormap='Blues',
    max_words=150,
    min_font_size=10,
    collocations=False
).generate(text_stemming_all)

plt.figure(figsize=(14, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.tight_layout(pad=0)
plt.savefig('wordcloud_20data.png', dpi=150, bbox_inches='tight')
plt.show()

print("Gambar 1. Word Cloud 20 Sampel Ulasan Halodoc (setelah stemming)")

"""#11. Preprocessing Full Dataset"""

print("Mulai preprocessing full data... (±10-15 menit, sabar ya)")

clean_df['text_clean']    = clean_df['content'].apply(cleaningText)
clean_df['text_case']     = clean_df['text_clean'].apply(casefoldingText)
clean_df['text_slang']    = clean_df['text_case'].apply(fix_slangwords)
clean_df['text_token']    = clean_df['text_slang'].apply(tokenizingText)
clean_df['text_stopword'] = clean_df['text_token'].apply(filteringText)
clean_df['text_stemming'] = clean_df['text_stopword'].apply(stemmingText)
clean_df['clean']         = clean_df['text_stemming'].apply(toSentence)

print(f"✅ Selesai! Total data: {len(clean_df)}")
clean_df[['content','clean']].head()

"""#12. Labeling Sentimen (InSet + Custom)"""

url_pos = "https://raw.githubusercontent.com/fajri91/InSet/master/positive.tsv"
url_neg = "https://raw.githubusercontent.com/fajri91/InSet/master/negative.tsv"
urllib.request.urlretrieve(url_pos, "positive.tsv")
urllib.request.urlretrieve(url_neg, "negative.tsv")

lex_pos = pd.read_csv('positive.tsv', sep='\t', header=None, names=['word','weight'])
lex_neg = pd.read_csv('negative.tsv', sep='\t', header=None, names=['word','weight'])

lexicon = {}
for _, row in lex_pos.iterrows():
    try: lexicon[row['word']] = float(row['weight'])
    except: pass
for _, row in lex_neg.iterrows():
    try: lexicon[row['word']] = float(row['weight'])
    except: pass

# Bobot manual konteks kesehatan
custom_lexicon = {
    'ramah':3,'bagus':3,'mudah':2,'bantu':2,'cepat':2,
    'baik':2,'puas':3,'mantap':3,'recommended':3,
    'recommend':3,'keren':3,'memuaskan':3,'praktis':2,
    'nyaman':2,'profesional':3,'responsif':3,'membantu':2,
    'lambat':-2,'lama':-2,'susah':-2,'sulit':-2,
    'kesalahan':-3,'gagal':-3,'kecewa':-3,'marah':-3,
    'buruk':-3,'jelek':-3,'parah':-3,'rugi':-2,
    'bohong':-3,'tipu':-3,'lemot':-2,'gangguan':-2,
}
lexicon.update(custom_lexicon)
print(f"Total kata di lexicon: {len(lexicon)}")

def get_sentiment(text):
    score = sum(lexicon.get(w, 0) for w in str(text).split())
    if score > 0:   return 'positif'
    elif score < 0: return 'negatif'
    else:           return 'netral'

clean_df['sentiment'] = clean_df['clean'].apply(get_sentiment)

print("\nDistribusi Sentimen:")
print(clean_df['sentiment'].value_counts())

"""#13. Simpan Data Berlabel"""

df_model = clean_df.copy()
df_model.reset_index(drop=True, inplace=True)

print(f"Total data: {len(df_model)}")
print(df_model['sentiment'].value_counts())

df_model.to_csv('halodoc_labeled.csv', index=False)
print("✅ Data berlabel tersimpan!")

"""#14. Visualisasi Distribusi Sentimen"""

import matplotlib.colors as mcolors
from matplotlib import cm

# Warna: negatif=merah, positif=hijau, netral=abu
color_map = {'negatif': '#e05c5c', 'positif': '#4caf7d', 'netral': '#9e9e9e'}
colors = [color_map.get(label, '#90caf9') for label in counts.index]

counts = df_model['sentiment'].value_counts()

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('Distribusi Sentimen Ulasan Halodoc di Google Play Store',
             fontsize=13, fontweight='bold', y=1.02)

# Bar chart
axes[0].bar(counts.index, counts.values, color=colors, edgecolor='white', linewidth=0.8)
axes[0].set_title('Bar Chart Distribusi Sentimen')
axes[0].set_xlabel('Sentimen')
axes[0].set_ylabel('Jumlah Ulasan')
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 5, str(v), ha='center', fontweight='bold')

# Pie chart
axes[1].pie(counts.values, labels=counts.index, colors=colors,
            autopct='%1.1f%%', startangle=90,
            wedgeprops={'edgecolor':'white','linewidth':1.5})
axes[1].set_title('Proporsi Sentimen (%)')

counts = df_model['sentiment'].value_counts()
colors = [color_map.get(label, '#90caf9') for label in counts.index]

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig('distribusi_sentimen.png', dpi=150, bbox_inches='tight')
plt.show()

print("Gambar 2. Distribusi Sentimen Ulasan Aplikasi Halodoc di Google Play Store (n=1.200)")
print(f"Negatif: {counts.get('negatif', 0)} ({counts.get('negatif',0)/counts.sum()*100:.1f}%)")
print(f"Positif: {counts.get('positif', 0)} ({counts.get('positif',0)/counts.sum()*100:.1f}%)")
print(f"Netral : {counts.get('netral',  0)} ({counts.get('netral', 0)/counts.sum()*100:.1f}%)")

"""#15. WordCloud per Sentimen"""

colormap_map = {'positif': 'Greens', 'negatif': 'Reds', 'netral': 'Blues'}
fig_labels   = {'positif': '3a',     'negatif': '3b',   'netral': '3c'}

for label in ['positif', 'negatif', 'netral']:
    subset = df_model[df_model['sentiment'] == label]['clean']
    if len(subset) == 0 or not ' '.join(subset).strip():
        print(f"Tidak ada data {label}")
        continue

    teks_gabung = ' '.join(subset)
    wc = WordCloud(
        width=1200, height=600,
        background_color='white',
        colormap=colormap_map[label],
        max_words=150,
        min_font_size=10,
        collocations=False
    ).generate(teks_gabung)

    fig_num = fig_labels[label]
    plt.figure(figsize=(14, 6))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'Gambar {fig_num}. Word Cloud Sentimen {label.capitalize()} — Ulasan Halodoc',
              fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'wordcloud_{label}.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Ringkasan kata teratas
    top5 = Counter(teks_gabung.split()).most_common(5)
    top5_str = ', '.join([f'{w} ({c}x)' for w,c in top5])
    print(f"Gambar {fig_num}. Word Cloud Sentimen {label.capitalize()} — Ulasan Halodoc (n={len(subset)})")
    print(f"  Top-5 kata: {top5_str}")
    print()

"""#16. Top N-gram per Sentimen"""

def plot_ngram(corpus, n, label, top_k=5):
    vec = CountVectorizer(ngram_range=(n, n)).fit(corpus)
    bag = vec.transform(corpus)
    freq = bag.sum(axis=0)
    words_freq = sorted([(w, freq[0,i]) for w,i in vec.vocabulary_.items()],
                        key=lambda x: x[1], reverse=True)[:top_k]
    words, counts = zip(*words_freq)
    gram = 'Unigram' if n==1 else 'Bigram'

    # Warna: positif=hijau, negatif=merah
    bar_color = '#4caf7d' if label == 'positif' else '#e05c5c'

    fig, ax = plt.subplots(figsize=(9,4))
    bars = ax.barh(list(reversed(list(words))),
                   list(reversed(list(counts))),
                   color=bar_color, edgecolor='white', linewidth=0.5)
    for bar, count in zip(bars, reversed(list(counts))):
        ax.text(bar.get_width()+0.5, bar.get_y()+bar.get_height()/2,
                str(count), va='center', fontsize=10, fontweight='bold')
    ax.set_title(f'Top-{top_k} {gram} — Sentimen {label.capitalize()}', fontweight='bold')
    ax.set_xlabel('Frekuensi')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.tight_layout()
    plt.savefig(f'{gram.lower()}_{label}.png', dpi=150, bbox_inches='tight')
    plt.show()
    return words_freq

fig_map = {'positif': {'uni':'4a','bi':'4b'}, 'negatif': {'uni':'4c','bi':'4d'}}
summary = {}

for label in ['positif', 'negatif']:
    corpus = df_model[df_model['sentiment']==label]['clean']
    if len(corpus) < 2: continue

    print(f"\n{'='*55}")
    print(f"  SENTIMEN {label.upper()}  (n={len(corpus)} ulasan)")
    print(f"{'='*55}")

    uni = plot_ngram(corpus, 1, label)
    fn_u = fig_map[label]['uni']
    print(f"Gambar {fn_u}. Top-5 Unigram Sentimen {label.capitalize()}")
    print(pd.DataFrame(uni, columns=['Kata','Frekuensi']).to_string(index=False))

    bi = plot_ngram(corpus, 2, label)
    fn_b = fig_map[label]['bi']
    print(f"\nGambar {fn_b}. Top-5 Bigram Sentimen {label.capitalize()}")
    print(pd.DataFrame(bi, columns=['Frasa','Frekuensi']).to_string(index=False))

    summary[label] = {'unigram': uni, 'bigram': bi}

# ── Tabel ringkasan Top-5 keyword (untuk copy ke artikel) ──
print("\n" + "="*55)
print("  RINGKASAN TOP-5 KEYWORD PER SENTIMEN")
print("="*55)
rows = []
for rank in range(5):
    rows.append({
        'Rank': rank+1,
        'Unigram Positif': summary['positif']['unigram'][rank][0] if rank < len(summary['positif']['unigram']) else '-',
        'Freq+':           summary['positif']['unigram'][rank][1] if rank < len(summary['positif']['unigram']) else 0,
        'Unigram Negatif': summary['negatif']['unigram'][rank][0] if rank < len(summary['negatif']['unigram']) else '-',
        'Freq-':           summary['negatif']['unigram'][rank][1] if rank < len(summary['negatif']['unigram']) else 0,
    })
df_summary = pd.DataFrame(rows)
print("\nTabel 3. Perbandingan Top-5 Kata Paling Sering (Unigram) per Sentimen")
print(df_summary.to_string(index=False))
df_summary.to_csv('top5_keywords.csv', index=False)
print("\n✅ File top5_keywords.csv tersimpan!")

"""#17. TF-IDF & Split Data"""

# Filter hanya positif & negatif untuk modeling
df_clf = df_model[df_model['sentiment'] != 'netral'].copy()
df_clf.reset_index(drop=True, inplace=True)
print(f"Data untuk modeling (tanpa netral): {len(df_clf)}")
print(df_clf['sentiment'].value_counts())

X = df_clf['clean']
y = df_clf['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Unigram TF-IDF
tfidf_uni = TfidfVectorizer(ngram_range=(1,1), max_features=5000)
X_train_uni = tfidf_uni.fit_transform(X_train)
X_test_uni  = tfidf_uni.transform(X_test)

# Bigram TF-IDF
tfidf_bi = TfidfVectorizer(ngram_range=(1,2), max_features=5000)
X_train_bi = tfidf_bi.fit_transform(X_train)
X_test_bi  = tfidf_bi.transform(X_test)

print(f"\nTrain: {len(X_train)} | Test: {len(X_test)}")

"""#18. Training & Evaluasi SGD"""

def train_evaluate(X_tr, X_te, y_tr, y_te, label):
    model = SGDClassifier(loss='hinge', max_iter=200, random_state=42)
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)
    print(f"\n{'='*45}")
    print(f"  SGD Classifier — {label}")
    print(f"{'='*45}")
    print(f"Accuracy : {accuracy_score(y_te, y_pred):.4f}")
    print(classification_report(y_te, y_pred))
    return model, y_pred

model_uni, pred_uni = train_evaluate(
    X_train_uni, X_test_uni, y_train, y_test, 'Unigram TF-IDF'
)
model_bi, pred_bi = train_evaluate(
    X_train_bi, X_test_bi, y_train, y_test, 'Bigram TF-IDF'
)

"""#19. Confusion Matrix"""

fig, axes = plt.subplots(1, 2, figsize=(12,4))
for ax, pred, title in zip(axes, [pred_uni, pred_bi], ['Unigram TF-IDF','Bigram TF-IDF']):
    cm_val = confusion_matrix(y_test, pred, labels=['positif','negatif'])
    sns.heatmap(cm_val, annot=True, fmt='d', ax=ax, cmap='Blues',
                xticklabels=['positif','negatif'],
                yticklabels=['positif','negatif'],
                linewidths=0.5)
    ax.set_title(f'Confusion Matrix — SGD {title}', fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("Gambar 5. Confusion Matrix SGD Classifier — Unigram TF-IDF (kiri) vs Bigram TF-IDF (kanan)")

"""#20. Tabel Perbandingan Hasil"""

hasil = pd.DataFrame({
    'Model'    : ['SGD + Unigram TF-IDF','SGD + Bigram TF-IDF'],
    'Accuracy' : [accuracy_score(y_test, pred_uni),
                  accuracy_score(y_test, pred_bi)],
    'Precision': [precision_score(y_test, pred_uni, average='weighted'),
                  precision_score(y_test, pred_bi,  average='weighted')],
    'Recall'   : [recall_score(y_test, pred_uni, average='weighted'),
                  recall_score(y_test, pred_bi,  average='weighted')],
    'F1-Score' : [f1_score(y_test, pred_uni, average='weighted'),
                  f1_score(y_test, pred_bi,  average='weighted')],
})
hasil = hasil.round(4)
print("Tabel 2. Perbandingan Hasil Evaluasi SGD Classifier (Unigram vs Bigram TF-IDF)")
print(hasil.to_string(index=False))
hasil.to_csv('hasil_evaluasi.csv', index=False)
print("\n✅ File hasil_evaluasi.csv tersimpan!")

"""#21. Download Semua File"""

from google.colab import files

file_list = [
    'halodoc_labeled.csv',
    'hasil_evaluasi.csv',
    'top5_keywords.csv',
    'distribusi_sentimen.png',
    'wordcloud_20data.png',
    'wordcloud_positif.png', 'wordcloud_negatif.png', 'wordcloud_netral.png',
    'confusion_matrix.png',
    'unigram_positif.png', 'unigram_negatif.png',
    'bigram_positif.png',  'bigram_negatif.png',
]

for f in file_list:
    try:
        files.download(f)
        print(f'✅ {f}')
    except:
        print(f'⚠️  {f} — tidak ditemukan, skip')